version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "devpass"
      POSTGRES_DB: "workouts"
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
